//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorePrice
    {
        public int CorePriceID { get; set; }
        public int CoreTypeID { get; set; }
        public double price { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual CoreType CoreType { get; set; }
    }
}
