//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Core()
        {
            this.Veneers = new HashSet<Veneer>();
        }
    
        public int CoreID { get; set; }
        public int OrderID { get; set; }
        public int CoreTypeID { get; set; }
        public int quantity { get; set; }
        public double length { get; set; }
        public double width { get; set; }
        public double thickness { get; set; }
        public double total_required_area { get; set; }
    
        public virtual CoreType CoreType { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Veneer> Veneers { get; set; }
    }
}
