//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veneer
    {
        public int VeneerID { get; set; }
        public int CoreID { get; set; }
        public int VeneerTypeID { get; set; }
        public int parallelLength { get; set; }
        public double crossLength { get; set; }
        public double thickness { get; set; }
        public bool isFaceVeneer { get; set; }
    
        public virtual Core Core { get; set; }
        public virtual VeneerType VeneerType { get; set; }
    }
}
